import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {SquaresFour,Briefcase,Users,ChatCircleText,Plus,MagnifyingGlass,ArrowRight,ArrowUp,ArrowLeft,CheckCircle,Clock,FilePdf,FileText,UploadSimple,CaretRight,WarningCircle,Check,ArrowSquareOut,X,ShieldCheck,List,EnvelopeSimple,DownloadSimple} from '@phosphor-icons/react';
import '@fontsource-variable/golos-text';
import './concept.css';

type CaseItem={id:string;name:string;client:string;kind:string;status:string;date:string;docs:number;owner:string};
type Doc={name:string;role:string;company:string;pages:number};
type Message={role:'user'|'assistant';text:string;source?:boolean;draft?:boolean};
const initialCases:CaseItem[]=[
 {id:'PL-024',name:'Страхование магазина',client:'ТОО «Точка Маркет»',kind:'Имущество',status:'На проверке',date:'24 сентября',docs:4,owner:'ДН'},
 {id:'PL-023',name:'Продление страхования склада',client:'ТОО «Север Логистик»',kind:'Продление',status:'Ждём документы',date:'26 сентября',docs:0,owner:'АК'},
 {id:'PL-022',name:'Страхование оборудования',client:'ТОО «Форма»',kind:'Имущество',status:'Черновик',date:'30 сентября',docs:0,owner:'ДН'},
 {id:'PL-021',name:'Страхование офиса',client:'ТОО «Точка Маркет»',kind:'Имущество',status:'Завершена',date:'15 сентября',docs:0,owner:'ДН'}
];
const initialDocs:Doc[]=[{name:'Запрос клиента',role:'Требования',company:'Точка Маркет',pages:1},{name:'Предложение Орбита.pdf',role:'Предложение',company:'Орбита Страхование',pages:2},{name:'Предложение Вектор.pdf',role:'Предложение',company:'Вектор Полис',pages:2},{name:'Предложение Сфера.pdf',role:'Предложение',company:'Сфера Защита',pages:2}];
const tabs=['Обзор','Документы','Сравнение','Уточнения','Отчёт','История'];
const initialQuestions=['Подтвердить покрытие затопления у «Вектора»','Запросить включение товарных запасов у «Вектора»','Уточнить вариант без подлимита у «Сферы»'];
const initialMessage:Message={role:'assistant',text:'Документы магазина собраны. В примере есть три важных расхождения: франшиза, товарные запасы и лимит по затоплению. С чего начнём?'};
const Btn=({children,onClick,primary=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{primary?:boolean})=><button {...props} className={`btn ${primary?'primary':''} ${props.className||''}`} onClick={onClick}>{children}</button>;
function App(){
 const [screen,setScreen]=useState<'case'|'cases'|'clients'|'assistant'>('case');const [tab,setTab]=useState('Обзор');
 const [cases,setCases]=useState(initialCases);const [selected,setSelected]=useState('PL-024');const current=cases.find(c=>c.id===selected)!;
 const [docs,setDocs]=useState<Record<string,Doc[]>>({'PL-024':initialDocs});const currentDocs=docs[selected]||[];const full=selected==='PL-024';
 const [search,setSearch]=useState('');const [filter,setFilter]=useState('Все');const [chatOpen,setChatOpen]=useState(()=>window.matchMedia('(min-width: 901px)').matches);const [menu,setMenu]=useState(false);
 const [messages,setMessages]=useState<Record<string,Message[]>>({'PL-024':[initialMessage]});const [input,setInput]=useState('');const [busy,setBusy]=useState(false);
 const [reviewed,setReviewed]=useState(false);const [done,setDone]=useState<string[]>([]);const [draft,setDraft]=useState(false);const [notice,setNotice]=useState('');
 const [newName,setNewName]=useState('');const [newClient,setNewClient]=useState('');const [newKind,setNewKind]=useState('Новое страхование');
 const sourceRef=useRef<HTMLDialogElement>(null);const newRef=useRef<HTMLDialogElement>(null);const fileRef=useRef<HTMLInputElement>(null);const logRef=useRef<HTMLDivElement>(null);
 const chatToggleRef=useRef<HTMLButtonElement>(null);const chatInputRef=useRef<HTMLTextAreaElement>(null);
 function closeChat(){setChatOpen(false);requestAnimationFrame(()=>chatToggleRef.current?.focus());}
 function toggleChat(){if(chatOpen){closeChat();return;}setChatOpen(true);requestAnimationFrame(()=>chatInputRef.current?.focus());}
 useEffect(()=>{if(!chatOpen||screen!=='case')return;const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!document.querySelector('dialog[open]')){event.preventDefault();closeChat();}};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[chatOpen,screen]);
 const scope=screen==='assistant'?'global':selected;const global=screen==='assistant';
 useEffect(()=>{logRef.current?.scrollTo({top:logRef.current.scrollHeight,behavior:'smooth'});},[messages,busy,chatOpen,scope]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 function openCase(id:string){setSelected(id);setScreen('case');setTab('Обзор');setInput('');setMenu(false);}
 function send(text:string){if(!text.trim()||busy)return;const key=scope;setInput('');setMessages(m=>({...m,[key]:[...(m[key]||[]),{role:'user',text}]}));setBusy(true);
   setTimeout(()=>{let answer:Message;
    if(global)answer={role:'assistant',text:'В демонстрационном списке: «Страхование магазина» — на проверке, срок 24 сентября. По складу «Север Логистик» ожидаются документы. Можно открыть заявку и продолжить работу с её источниками.'};
    else if(!full)answer={role:'assistant',text:'В этой заявке пока нет подготовленного анализа. Макет показывает структуру: добавьте документы и укажите задачу. Настоящий AI-анализ здесь не подключён.'};
    else if(/письм|уточн|спрос/i.test(text))answer={role:'assistant',text:'Черновик для «Вектора»\n\nДобрый день! Просим подтвердить покрытие затопления при аварии водопровода, предложить включение товарных запасов и рассчитать вариант с франшизой не более 100 000 ₸. Просим прислать обновлённое предложение с указанием изменений.',draft:true};
    else if(/франш|дешев|разниц|расхожд|провер/i.test(text))answer={role:'assistant',text:'У «Вектора» франшиза — 1% страховой суммы. При сумме 80 000 000 ₸ это 800 000 ₸, в 8 раз выше ограничения клиента.\n\nТоварные запасы исключены. Покрытие затопления в предложении не описано: его нужно уточнить, а не считать отсутствующим.',source:true};
    else if(/итог|клиент|отчёт|отчет/i.test(text))answer={role:'assistant',text:'Для обсуждения с клиентом: «Вектор» дешевле, но не включает товары и предусматривает франшизу 800 000 ₸. У «Сферы» затопление ограничено 5 млн ₸. Перед выбором нужно сверить условия и получить ответы страховщиков.',source:true};
    else answer={role:'assistant',text:'Это интерактивный макет с заранее подготовленными ответами. Попробуйте «Что нужно проверить?», «Объясни франшизу» или «Подготовь письмо страховщику». В рабочем продукте ответ будет строиться по документам этой заявки.'};
    setMessages(m=>({...m,[key]:[...(m[key]||[]),answer]}));setBusy(false);},650);
 }
 function download(){const text=`POLIS — УЧЕБНЫЙ ОТЧЁТ\n${current.name}\n${current.client}\nВсе компании и условия вымышлены.\n\nОрбита: 420 000 ₸; франшиза 100 000 ₸.\nВектор: 365 000 ₸; франшиза 800 000 ₸; товары исключены; затопление требует уточнения.\nСфера: 485 000 ₸; франшиза 50 000 ₸; подлимит затопления 5 000 000 ₸.\n\nПроверка отмечена пользователем в макете. Это не страховая рекомендация.`;
  const questions='\n\nУТОЧНЕНИЯ\n'+initialQuestions.map(q=>`${done.includes(q)?'[Решено]':'[Открыто]'} ${q}`).join('\n');const url=URL.createObjectURL(new Blob([text+questions],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Polis-учебный-отчёт.txt';a.click();URL.revokeObjectURL(url);
 }
 const chat=<aside id={global?'workspace-assistant':'case-assistant'} className={`chat ${global?'global-chat':'case-assistant'}`} aria-label="Помощник Polis"><div className="chat-heading"><span className="assistant-logo"><ChatCircleText size={20}/></span><div><strong>Помощник Polis</strong><small>{global?'По всем заявкам':'В контексте этой заявки'}</small></div>{!global&&<button className="icon-btn" aria-label="Закрыть чат" onClick={closeChat}><X size={18}/></button>}</div><div className="scope"><ShieldCheck size={15}/>{global?'4 учебные заявки':'Только «'+current.client+'»'}</div><div className="chat-log" ref={logRef} aria-live="polite">{(messages[scope]||[{role:'assistant',text:global?'Помогу сориентироваться в заявках. Какие требуют внимания и где не хватает документов?':'Чем помочь по этой заявке?'}]).map((m,i)=><div key={i} className={`message ${m.role}`}><div className="message-label">{m.role==='user'?'Вы':'Polis'}</div><p>{m.text}</p>{m.source&&<button className="citation" onClick={()=>sourceRef.current?.showModal()}><FilePdf size={15}/>Вектор · страницы 1–2<ArrowSquareOut size={13}/></button>}{m.draft&&<Btn onClick={()=>{setDraft(true);setNotice('Черновик добавлен в «Уточнения». Письмо не отправлено.');}}>Добавить в уточнения<Plus size={14}/></Btn>}{global&&m.role==='assistant'&&i>0&&<Btn onClick={()=>openCase('PL-024')}>Открыть магазин<ArrowRight size={14}/></Btn>}</div>)}{busy&&<div className="thinking">Готовим демонстрационный ответ…</div>}</div><div className="chat-bottom"><div className="suggestions">{(global?['Что требует внимания?']:['Что нужно проверить?','Подготовь письмо']).map(q=><button disabled={busy} key={q} onClick={()=>send(q)}>{q}<ArrowUp size={12}/></button>)}</div><form onSubmit={e=>{e.preventDefault();send(input);}}><textarea ref={chatInputRef} aria-label="Сообщение помощнику" placeholder={global?'Спросите про ваши заявки…':'Задайте вопрос по документам…'} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send(input);}}}/><div className="composer-bottom"><span>{global?'Обзор рабочего пространства':`${currentDocs.length} источника в заявке`}</span><button className="send" disabled={!input.trim()||busy} aria-label="Отправить сообщение"><ArrowUp size={18}/></button></div></form><small className="chat-disclaimer">Макет: ответы подготовлены заранее. Выводы проверяет человек.</small></div></aside>;
 return <div className={`concept ${screen==='case'&&chatOpen?'with-assistant':''}`}><div className="demo-banner"><span>Концепция Polis</span><span>Вымышленные данные · изменения сохраняются до обновления страницы</span><a href="/">К рабочей версии <ArrowSquareOut size={13}/></a></div><div className="shell"><nav className={`sidebar ${menu?'mobile-open':''}`} aria-label="Основная навигация"><a href="#" className="brand" onClick={e=>{e.preventDefault();setScreen('cases');setMenu(false);}}><span className="brand-mark"><ShieldCheck size={23} weight="bold"/></span>polis<span className="brand-dot">.</span></a><div className="workspace"><span className="workspace-avatar">П</span><div>Моё пространство<small>Страховой брокер</small></div></div><div className="nav-group">{[{key:'cases',name:'Заявки',icon:Briefcase},{key:'clients',name:'Клиенты',icon:Users},{key:'assistant',name:'Помощник',icon:ChatCircleText}].map(({key,name,icon:Icon})=><button key={key} className={(screen===key||(key==='cases'&&screen==='case'))?'active':''} onClick={()=>{setScreen(key as typeof screen);setMenu(false);setSearch('');}}><Icon size={20}/>{name}{key==='cases'&&<span className="nav-count">{cases.length}</span>}</button>)}</div><div className="recent"><p>Недавние заявки</p>{cases.slice(0,3).map(c=><button className={screen==='case'&&c.id===selected?'selected':''} onClick={()=>openCase(c.id)} key={c.id}><span className={`dot ${c.status==='На проверке'?'amber':''}`}/><span>{c.client}<small>{c.name}</small></span></button>)}</div><div className="sidebar-footer"><span className="avatar">ДН</span><div>Динмухамед<small>Рабочее пространство</small></div></div></nav><main><header className="topbar"><button className="icon-btn mobile-menu" aria-label="Открыть меню" onClick={()=>setMenu(!menu)}><List size={22}/></button><div className="breadcrumb"><button onClick={()=>setScreen('cases')}>Рабочее пространство</button><CaretRight size={13}/><span>{screen==='case'?current.id:screen==='clients'?'Клиенты':screen==='assistant'?'Помощник':'Заявки'}</span></div><div className="topbar-right"><span className="tiny-dot"/>Личный кабинет<span className="avatar small">ДН</span></div></header>
 {screen==='case'?<><div className="case-header"><div className="title-row"><div><div className="client-line"><Briefcase size={16}/>{current.client}<span>·</span>{current.kind}</div><h1>{current.name}</h1></div><Btn onClick={()=>setTab('Отчёт')}><FileText size={17}/>Подготовить отчёт</Btn></div><div className="case-meta"><span className={`status ${current.status==='На проверке'?'warn':''}`}>{current.status==='На проверке'?<WarningCircle size={14}/>:<Clock size={14}/>} {reviewed&&full?'Проверка завершена':current.status}</span><span><Clock size={14}/>До {current.date.toLowerCase()}</span><span><span className="avatar mini">{current.owner}</span>Ответственный</span><button ref={chatToggleRef} onClick={toggleChat} aria-expanded={chatOpen} aria-controls="case-assistant" className="chat-toggle"><ChatCircleText size={17}/>{chatOpen?'Скрыть чат':'Открыть чат'}</button></div><div className="tabs" role="tablist" aria-label="Разделы заявки">{tabs.map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}{t==='Документы'&&<span>{currentDocs.length}</span>}{t==='Уточнения'&&full&&<span>{3-done.length}</span>}</button>)}</div></div><div className="case-layout"><div className="case-content">
 {tab==='Обзор'&&<><div className="section-head"><h2>Что происходит по заявке</h2><span className="muted">{full?'Обновлено сегодня, 10:42':'Учебный пример'}</span></div><ol className="stages">{['Документы','Анализ','Проверка','Готовый отчёт'].map((s,i)=><li key={s} className={full?(i<2?'complete':i===2?'current':''):i===0?'current':''}><span>{full&&i<2?<Check size={12}/>:i+1}</span>{s}</li>)}</ol>{full?<><section className="next-step"><div className="next-icon"><WarningCircle size={23}/></div><div><h3>{reviewed?'Проверка отмечена завершённой':'Проверьте расхождения перед отправкой'}</h3><p>{reviewed?'Можно подготовить учебный отчёт. Открытые вопросы останутся в нём.':'В трёх предложениях есть условия, которые отличаются от запроса клиента.'}</p><Btn primary onClick={()=>setTab(reviewed?'Отчёт':'Сравнение')}>{reviewed?'К отчёту':'Перейти к сравнению'}<ArrowRight size={15}/></Btn></div></section><div className="section-head"><h2>Требует внимания</h2><span className="count">3</span></div><div className="findings">{[{title:'Франшиза выше требования в 8 раз',text:'Вектор Полис · 800 000 ₸ вместо максимум 100 000 ₸',label:'Расхождение'},{title:'Товарные запасы не застрахованы',text:'Вектор Полис · клиент просил включить товары',label:'Расхождение'},{title:'Затопление ограничено 5 млн ₸',text:'Сфера Защита · запрошено без отдельного подлимита',label:'Подлимит'}].map((f,i)=><button key={f.title} className="finding" onClick={()=>i===2?setTab('Сравнение'):sourceRef.current?.showModal()}><span className="finding-symbol"><WarningCircle size={18}/></span><span><strong>{f.title}</strong><small>{f.text}</small></span><CaretRight size={16}/></button>)}</div><div className="section-head"><h2>Задача клиента</h2><Btn onClick={()=>{setTab('Документы');}}>Источники<ArrowRight size={13}/></Btn></div><div className="brief"><p>Защитить магазин, оборудование и товары от пожара и аварии водопровода. Проверить три предложения перед покупкой.</p><dl><div><dt>Страховая сумма</dt><dd>80 000 000 ₸</dd></div><div><dt>Срок</dt><dd>12 месяцев</dd></div><div><dt>Макс. франшиза</dt><dd>100 000 ₸</dd></div></dl></div></>:<div className="empty"><UploadSimple size={34}/><h2>Сначала соберите документы</h2><p>Добавьте запрос клиента и предложения страховщиков. Каждому файлу можно назначить роль.</p><Btn primary onClick={()=>setTab('Документы')}>Добавить документы</Btn></div>}</>}
 {tab==='Документы'&&<><div className="section-head"><div><h2>Документы заявки</h2><p className="muted">Роль документа определяет, как использовать его в анализе.</p></div><Btn primary onClick={()=>fileRef.current?.click()}><Plus size={16}/>Добавить</Btn></div><input type="file" accept=".pdf,.txt,.docx" ref={fileRef} hidden multiple onChange={e=>{const added=Array.from(e.target.files||[]).map(f=>({name:f.name,role:'Не назначена',company:'Назначьте источник',pages:0}));setDocs(d=>({...d,[selected]:[...(d[selected]||[]),...added]}));setReviewed(false);setNotice('В макет добавлены только названия файлов. Содержимое не загружалось и не анализировалось.');e.target.value='';}}/><div className="doc-list">{currentDocs.map((d,i)=><div className="doc-row" key={i}><span className="file-icon">{i===0&&full?<FileText size={23}/>:<FilePdf size={23}/>}</span><div className="doc-info"><strong>{d.name}</strong><small>{d.company} · {d.pages?`${d.pages} стр. · v1`:'Только имя файла'}</small></div><select aria-label={`Роль ${d.name}`} value={d.role} onChange={e=>{const role=e.target.value;setDocs(all=>({...all,[selected]:currentDocs.map((x,j)=>j===i?{...x,role}:x)}));setReviewed(false);}}>{['Требования','Предложение','Действующий полис','Правила страхования','Переписка','Не назначена'].map(r=><option key={r}>{r}</option>)}</select></div>)}</div><button className="upload-area" onClick={()=>fileRef.current?.click()}><UploadSimple size={28}/><strong>Добавить файлы в заявку</strong><span>PDF, DOCX или TXT · демонстрация назначения ролей</span></button><p className="subnote">В рабочей версии после загрузки: распознавание → проверка комплектности → анализ. Новая версия документа потребует повторной проверки выводов.</p></>}
 {tab==='Сравнение'&&(full?<><div className="section-head"><div><h2>Предложения страховщиков</h2><p className="muted">Сопоставлены с запросом клиента. Данные учебные.</p></div></div><div className="comparison-wrap"><table><thead><tr><th>Условие</th><th>Орбита</th><th>Вектор</th><th>Сфера</th></tr></thead><tbody>{[['Цена за год','420 000 ₸','365 000 ₸','485 000 ₸'],['Страховая сумма','80 млн ₸','80 млн ₸','80 млн ₸'],['Товарные запасы','Включены','Исключены','Включены'],['Затопление','Без подлимита','Нужно уточнить','Лимит 5 млн ₸'],['Франшиза','100 000 ₸','800 000 ₸','50 000 ₸']].map((r,i)=><tr key={r[0]}>{r.map((v,j)=>j===0?<th key={j}>{v}</th>:<td key={j} className={i>1&&(j===2||(i===3&&j===3))?'difference':''}>{i===4&&j===2?<button className="cell-source" onClick={()=>sourceRef.current?.showModal()}>{v}<span>1% от страховой суммы · стр. 2<ArrowSquareOut size={12}/></span></button>:v}</td>)}</tr>)}</tbody></table></div><div className="review-box"><ShieldCheck size={23}/><div><strong>Проверка остаётся за брокером</strong><p>Сверьте значения и исключения с оригиналами. Открытые вопросы сохраняются в отчёте.</p></div></div><label className="review-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Для демонстрации: отметить проверку сравнения</label><Btn primary disabled={!reviewed} onClick={()=>setTab('Отчёт')}>Подготовить отчёт<ArrowRight size={15}/></Btn></>:<div className="empty"><SquaresFour size={32}/><h2>Сравнение появится после анализа</h2><p>В этом макете заполнен пример магазина «Точка».</p><Btn onClick={()=>openCase('PL-024')}>Открыть заполненный пример</Btn></div>)}
 {tab==='Уточнения'&&<><div className="section-head"><div><h2>Что нужно уточнить</h2><p className="muted">Из вопроса — в действие. Отправкой управляет человек.</p></div></div>{full?initialQuestions.map(q=><label className="question" key={q}><input type="checkbox" checked={done.includes(q)} onChange={()=>setDone(d=>d.includes(q)?d.filter(x=>x!==q):[...d,q])}/><span className={done.includes(q)?'struck':''}>{q}</span><span className="muted">{done.includes(q)?'Решено':'Открыто'}</span></label>):<p className="muted">После анализа здесь появятся вопросы по документам.</p>}{full&&<section className="draft"><EnvelopeSimple size={23}/><h3>{draft?'Черновик из чата':'Письмо страховщику'}</h3><p>Добрый день! Просим подтвердить покрытие затопления, включить товарные запасы и предложить вариант с франшизой не более 100 000 ₸.</p><Btn onClick={async()=>{try{await navigator.clipboard.writeText('Добрый день! Просим подтвердить покрытие затопления, включить товарные запасы и предложить вариант с франшизой не более 100 000 ₸.');setNotice('Текст письма скопирован. Ничего не отправлено.');}catch{setNotice('Буфер обмена недоступен. Выделите и скопируйте текст письма.');}}}>Скопировать текст</Btn><small>Черновик · не отправлен</small></section>}</>}
 {tab==='Отчёт'&&<><div className="section-head"><div><h2>Предложение клиенту</h2><p className="muted">Выводы, сравнение и вопросы в одном документе.</p></div></div><div className="report-paper"><div className="report-top"><b>polis.</b><span>Учебный отчёт</span></div><h2>{current.name}</h2><p>{current.client}</p><hr/><h3>Краткий итог</h3><p>{full?'У «Вектора» ниже стоимость, но исключены товары и выше франшиза. У «Сферы» действует подлимит по затоплению. Сравнение необходимо учитывать вместе с ответами страховщиков.':'Добавьте документы и подготовьте анализ, чтобы сформировать итог.'}</p><h3>Открытые вопросы</h3><p>{full?`${3-done.length} из 3 вопросов требуют ответа. Статус сохраняется в отчёте.`:'Анализ ещё не выполнен.'}</p></div>{!reviewed&&<p className="report-gate"><ShieldCheck size={18}/>Сначала отметьте проверку на вкладке «Сравнение».</p>}<Btn primary disabled={!full||!reviewed} onClick={download}><DownloadSimple size={17}/>Скачать учебный отчёт TXT</Btn></>}
 {tab==='История'&&<><div className="section-head"><h2>История заявки</h2></div><p className="muted">Фиксируем события и версии, а не каждое действие человека.</p><div className="timeline">{(full?[['10:42','Анализ подготовлен','Polis · 3 предложения сопоставлены с требованиями'],['10:40','Добавлены предложения','Динмухамед · Орбита, Вектор, Сфера'],['10:35','Указаны требования клиента','Динмухамед · сумма, риски, франшиза'],['10:30','Создана заявка','Динмухамед · ТОО «Точка Маркет»']]:[['Сейчас','Создана учебная заявка',current.client]]).map(([time,title,desc])=><div key={title}><time>{time}</time><span className="timeline-point"/><section><strong>{title}</strong><p>{desc}</p></section></div>)}</div></>}
 </div></div></>:<div className="page-content">{screen==='assistant'?<><h1>Помощник по рабочему пространству</h1><p className="page-intro">Найдите нужную заявку и следующий шаг. Детали документов — в чате конкретной заявки.</p>{chat}</>:<><div className="title-row"><div><h1>{screen==='clients'?'Клиенты':'Заявки'}</h1><p className="page-intro">{screen==='clients'?'Вся история работы с компанией в одном месте.':'От первого документа до проверенного предложения.'}</p></div><Btn primary onClick={()=>newRef.current?.showModal()}><Plus size={17}/>Новая заявка</Btn></div>{screen==='clients'?<div className="clients-list">{Array.from(new Set(cases.map(c=>c.client))).map(client=><section key={client}><div className="client-heading"><span className="client-square"><Users size={22}/></span><div><h2>{client}</h2><p className="muted">{cases.filter(c=>c.client===client).length} заявки · учебная компания</p></div></div>{cases.filter(c=>c.client===client).map(c=><button key={c.id} onClick={()=>openCase(c.id)}><span>{c.name}</span><span className="muted">{c.status}</span><ArrowRight size={16}/></button>)}</section>)}</div>:<><div className="list-tools"><div className="filters">{['Все','На проверке','Ждём документы'].map(f=><button aria-pressed={filter===f} className={f===filter?'active':''} key={f} onClick={()=>setFilter(f)}>{f}{f==='Все'&&<span>{cases.length}</span>}</button>)}</div><label className="search"><MagnifyingGlass size={17}/><input aria-label="Поиск заявок" placeholder="Клиент или заявка" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="cases-table"><div className="cases-table-head"><span>Заявка / клиент</span><span>Этап</span><span>Срок</span><span>Ответственный</span></div>{cases.filter(c=>(filter==='Все'||c.status===filter)&&`${c.name} ${c.client}`.toLowerCase().includes(search.toLowerCase())).map(c=><button className="case-row" onClick={()=>openCase(c.id)} key={c.id}><span className="case-row-name"><span className="case-icon"><Briefcase size={21}/></span><span><strong>{c.name}</strong><small>{c.client} · {c.id}</small></span></span><span className={`status ${c.status==='На проверке'?'warn':''}`}>{c.status}</span><span className="due">{c.date}</span><span className="owner"><span className="avatar mini">{c.owner}</span><CaretRight size={16}/></span></button>)}{!cases.some(c=>(filter==='Все'||c.status===filter)&&`${c.name} ${c.client}`.toLowerCase().includes(search.toLowerCase()))&&<div className="empty"><MagnifyingGlass size={30}/><h2>Заявок не найдено</h2><p>Измените запрос или сбросьте фильтр.</p><Btn onClick={()=>{setSearch('');setFilter('Все');}}>Сбросить поиск</Btn></div>}</div><p className="list-footer">Каждая заявка — отдельная задача, документы, обсуждение и результат.</p></>}</>}</div>}
 </main></div>{screen==='case'&&chatOpen&&chat}<dialog ref={sourceRef} className="source-dialog"><div className="dialog-head"><div><h2>Источник вывода</h2><p className="muted">Предложение Вектор.pdf · учебный документ</p></div><button className="icon-btn" aria-label="Закрыть источник" onClick={()=>sourceRef.current?.close()}><X size={21}/></button></div><div className="source-sheet"><FilePdf size={30}/><h3>Вектор Полис</h3><p className="muted">Фрагмент · страница 2</p><blockquote>Франшиза: 1% страховой суммы.</blockquote><p>Страховая сумма: 80 000 000 ₸.</p><p className="math">80 000 000 × 1% = <strong>800 000 ₸</strong></p><p>Запрос клиента: не более 100 000 ₸.</p><hr/><p className="muted">Страница 1: застрахованы помещение и оборудование; товарные запасы исключены.</p></div><p className="subnote">В рабочей версии здесь открывается оригинальная страница PDF. В концепции показан учебный фрагмент.</p><Btn primary onClick={()=>{sourceRef.current?.close();setTab('Сравнение');}}>Вернуться к сравнению</Btn></dialog><dialog ref={newRef} className="new-dialog"><form onSubmit={e=>{e.preventDefault();const id=`PL-${String(cases.length+21).padStart(3,'0')}`;setCases(cs=>[{id,name:newName.trim(),client:newClient.trim(),kind:newKind,status:'Черновик',date:'Не назначен',docs:0,owner:'ДН'},...cs]);newRef.current?.close();setNewName('');setNewClient('');openCase(id);}}><div className="dialog-head"><h2>Новая заявка</h2><button type="button" className="icon-btn" aria-label="Закрыть создание заявки" onClick={()=>newRef.current?.close()}><X size={20}/></button></div><p className="muted">Одна заявка — одна задача по страхованию.</p><label>Клиент<input required value={newClient} onChange={e=>setNewClient(e.target.value)} placeholder="Например, ТОО «Точка Маркет»"/></label><label>Название задачи<input required value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Страхование нового склада"/></label><label>Тип задачи<select value={newKind} onChange={e=>setNewKind(e.target.value)}><option>Новое страхование</option><option>Продление</option><option>Проверка полиса</option></select></label><Btn primary type="submit" disabled={!newName.trim()||!newClient.trim()}>Создать заявку<ArrowRight size={16}/></Btn><p className="subnote">Учебная заявка сохранится до обновления страницы.</p></form></dialog>{notice&&<div className="toast" role="status"><CheckCircle size={20}/>{notice}<button className="icon-btn" aria-label="Закрыть уведомление" onClick={()=>setNotice('')}><X size={16}/></button></div>}</div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
