import {apiFetch} from './api';
import {useEffect,useRef,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {ArrowUp,ChatCircleText,FilePdf,ShieldCheck,X,ArrowRight,Plus,ArrowsClockwise} from '@phosphor-icons/react';
import {type Case,type ChatMessage,type Evidence,isCurrent} from '../shared/types';

export default function Assistant({item,cases,onClose,onSource,onOpenCase,onDraft,disabled=false,inline=false}:{item?:Case;cases:Case[];onClose:()=>void;onSource:(source:Evidence)=>void;onOpenCase:(id:string)=>void;onDraft:(text:string)=>Promise<void>;disabled?:boolean;inline?:boolean}){
 const [messages,setMessages]=useState<ChatMessage[]>([]);const [input,setInput]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [mobile,setMobile]=useState(()=>matchMedia('(max-width:900px)').matches);
 const [saving,setSaving]=useState(false);const [saved,setSaved]=useState('');const log=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLTextAreaElement>(null);const endpoint=item?`/cases/${item.id}/chat`:'/chat';
 useEffect(()=>{const query=matchMedia('(max-width:900px)');const changed=()=>setMobile(query.matches);query.addEventListener('change',changed);return()=>query.removeEventListener('change',changed);},[]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);apiFetch(endpoint,{signal:abort.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setMessages(data);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[endpoint,reload]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});},[messages,busy]);
 async function send(value:string){if(!value.trim()||busy||disabled||loading)return;setError('');setBusy(true);setInput(value);try{const r=await apiFetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value})});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessages(data);setInput('');}catch(e){setError((e as Error).message);}finally{setBusy(false);inputRef.current?.focus();}}
 const content=<><div className="assistant-heading"><span className="assistant-symbol"><ChatCircleText size={22}/></span><div>{mobile&&!inline?<Dialog.Title>Помощник Polis</Dialog.Title>:<h2>Помощник Polis</h2>}<p>{item?'В контексте этой заявки':'По рабочему пространству'}</p></div>{!inline&&<button className="icon-button" aria-label="Закрыть помощника" onClick={onClose}><X size={21}/></button>}</div><div className="assistant-scope"><ShieldCheck size={16}/><span>{item?`${item.client} · ${item.title}`:'Сводка по заявкам · без передачи PDF'}</span></div>
 {item&&!isCurrent(item)&&item.offers.length>0&&<p className="assistant-version">Сравнение не актуально. Помощник получает текущие PDF; обновите анализ перед проверкой.</p>}
 <div className="assistant-log" ref={log} role="log" aria-label="История разговора" aria-live="polite" aria-busy={busy}>
 {loading?<p className="muted">Загружаем разговор…</p>:messages.length===0&&<div className="assistant-welcome"><ChatCircleText size={30}/><h3>{item?'Разберёмся в условиях':'Что требует внимания?'}</h3><p>{item?'Спросите о документах, различиях предложений или подготовьте вопросы страховщику. Ответы с источниками можно проверить в PDF.':'Найдите заявку, посмотрите её этап и срок. Для вопросов об условиях откройте помощника внутри заявки.'}</p></div>}
 {messages.map(m=><article className={`assistant-message ${m.role}`} key={m.id}><div className="assistant-label">{m.role==='user'?'Вы':'Polis'}<time>{new Date(m.createdAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</time></div>{item&&m.revision!==undefined&&m.revision!==item.revision&&<small className="assistant-old">Ответ относится к предыдущей версии заявки</small>}<p>{m.text}</p>{m.sources?.map((s,i)=><button className="assistant-citation" key={`${s.fileId}-${i}`} onClick={()=>onSource(s)}><FilePdf size={16}/>{item?.offers.flatMap(o=>o.documents).concat(item.attachments||[]).find(d=>d.id===s.fileId)?.name||'Документ'} · стр. {s.page}</button>)}{m.caseIds?.map(id=>{const c=cases.find(c=>c.id===id);return c&&<button className="assistant-case-link" key={id} onClick={()=>onOpenCase(id)}>{c.title}<ArrowRight size={16}/></button>;})}{m.draft&&<div className="assistant-draft"><p>{m.draft}</p>{item&&<button className="button secondary small-button" disabled={saving||disabled||saved===m.id} onClick={async()=>{setSaving(true);try{await onDraft(m.draft!);setSaved(m.id);}catch(e){setError((e as Error).message);}finally{setSaving(false);}}}><Plus size={15}/>{saved===m.id?'Сохранено в уточнениях':'Сохранить в уточнениях'}</button>}</div>}</article>)}
 {busy&&<div className="assistant-pending"><p>{input}</p><span>Помощник изучает контекст…</span></div>}
 </div>
 <div className="assistant-composer">{error&&<div className="assistant-error" role="alert"><p>{error}</p>{!messages.length&&<button className="text-button" onClick={()=>setReload(v=>v+1)}><ArrowsClockwise size={14}/>Обновить разговор</button>}</div>}<div className="assistant-prompts">{(item?['Что нужно проверить?','Подготовь письмо']:['Какие заявки требуют внимания?']).map(q=><button key={q} disabled={busy||disabled||loading} onClick={()=>void send(q)}>{q}<ArrowUp size={13}/></button>)}</div><form onSubmit={e=>{e.preventDefault();void send(input);}}><textarea ref={inputRef} value={input} maxLength={6000} aria-label="Сообщение помощнику" placeholder={item?'Спросите по документам заявки…':'Спросите про заявки…'} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send(input);}}}/><div><span>{item?`${item.offers.filter(o=>o.documents.length).length+(item.attachments?.length||0)} актуальных PDF`:'Навигация по заявкам'}</span><button disabled={!input.trim()||busy||disabled||loading} aria-label="Отправить сообщение"><ArrowUp size={21}/></button></div></form><p className="assistant-disclaimer">{item?.demo?'Учебный режим · ответы по данным примера, без AI.':item?'Актуальные PDF и требования отправляются модели. Проверяйте ответы по оригиналам.':'Сводка по заявкам отправляется модели. Документы не передаются.'}</p></div></>;
 if(mobile&&!inline)return <Dialog.Root open onOpenChange={v=>!v&&onClose()}><Dialog.Portal><Dialog.Overlay className="assistant-mobile-overlay"/><Dialog.Content aria-describedby={undefined} className="polis-assistant assistant-mobile" onOpenAutoFocus={e=>{e.preventDefault();inputRef.current?.focus();}}>{content}</Dialog.Content></Dialog.Portal></Dialog.Root>;
 return <aside id="polis-assistant" className={`polis-assistant ${inline?'assistant-inline':''}`} aria-label="Помощник Polis">{content}</aside>;
}
