import {useState} from 'react';
import {ArrowRight,Buildings,CheckCircle,Clock,FilePdf,FileText,Plus,ShieldCheck,WarningCircle} from '@phosphor-icons/react';
import {caseStage,caseQuestions,allReviewed,isCurrent,FIELDS,type Case,type FieldKey,type Offer,type DocumentRole,DOCUMENT_ROLES} from '../shared/types';
export function Clients({cases,open,create}:{cases:Case[];open:(id:string)=>void;create:()=>void}){
 const [search,setSearch]=useState('');const groups=Array.from(new Set(cases.map(c=>c.client))).filter(name=>name.toLowerCase().includes(search.toLowerCase()));
 return <><div className="page-heading"><div><h1>Клиенты</h1><p>Документы, задачи и история работы с каждой компанией.</p></div><button className="button primary" onClick={create}><Plus size={18}/>Новая заявка</button></div><label className="field client-search">Найти клиента<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Название компании"/></label><div className="workspace-clients">{groups.map(name=><section key={name}><div className="client-group-heading"><Buildings size={24}/><div><h2>{name}</h2><p>{cases.filter(c=>c.client===name).length} заявок</p></div></div>{cases.filter(c=>c.client===name).map(c=><button key={c.id} onClick={()=>open(c.id)}><div><strong>{c.title}</strong><span>{c.demo?'Учебный пример':caseStage(c)}{c.dueDate&&` · до ${c.dueDate}`}</span></div><ArrowRight size={18}/></button>)}</section>)}</div>{!groups.length&&<div className="empty"><Buildings size={32}/><h3>Клиенты не найдены</h3><p>Клиент появляется после создания первой заявки.</p></div>}</>;
}
export function Overview({c,busy,onTab,onFinding,onDetails,onAnalyze}:{c:Case;busy:boolean;onTab:(tab:'documents'|'compare'|'questions'|'report')=>void;onFinding:(offer:Offer,field:FieldKey)=>void;onDetails:(details:{dueDate:string;owner:string})=>Promise<void>;onAnalyze:()=>void}){
 const [owner,setOwner]=useState(c.owner||'');const [dueDate,setDueDate]=useState(c.dueDate||'');const [saved,setSaved]=useState(false);const [error,setError]=useState('');const current=isCurrent(c);const checked=allReviewed(c);const questions=caseQuestions(c).filter(q=>!q.resolved);
 return <div className="workspace-overview"><div className="overview-next"><ShieldCheck size={27}/><div><h2>{checked?'Сравнение проверено':current?'Проверьте условия по источникам':c.offers.length>=2?'Документы готовы к анализу':'Соберите предложения страховщиков'}</h2><p>{checked?'Подготовьте итоговый отчёт и сохраните открытые вопросы для клиента.':current?`Открытых уточнений: ${questions.length}. Ответы и проверка сохраняются в этой заявке.`:'Добавьте минимум два предложения. Требования, правила и переписку можно приложить отдельно.'}</p><button className="button primary" disabled={busy} onClick={()=>current?onTab(checked?'report':'compare'):c.offers.length>=2?onAnalyze():onTab('documents')}>{current?checked?'Подготовить отчёт':'Перейти к проверке':c.offers.length>=2?'Запустить анализ':'Добавить документы'}<ArrowRight size={16}/></button></div></div>
 <div className="section-heading"><div><h2>Требует внимания</h2><p>{current?'Выводы по актуальному сравнению':'После анализа здесь появятся расхождения и неизвестные условия.'}</p></div></div>{current&&questions.length?<div className="overview-findings">{questions.slice(0,5).map(q=><button key={q.id} onClick={()=>onFinding(c.offers.find(o=>o.id===q.offerId)!,q.field)}><WarningCircle size={20}/><span><strong>{q.offer} · {q.title}</strong><small>{q.text}</small></span><ArrowRight size={16}/></button>)}</div>:<p className="workspace-note">{current?'Открытых вопросов нет. Отметка ответа не заменяет проверку исходного условия.':'Сохранённые прежние выводы не используются как актуальные.'}</p>}
 <div className="section-heading"><h2>Организация работы</h2><span className="badge">{caseStage(c)}</span></div><form className="case-details-form" onSubmit={async e=>{e.preventDefault();setError('');try{await onDetails({owner,dueDate});setSaved(true);}catch(e){setError((e as Error).message);}}}><label className="field">Ответственный<input maxLength={100} value={owner} onChange={e=>{setOwner(e.target.value);setSaved(false);}} placeholder="Имя сотрудника"/></label><label className="field">Срок<input type="date" value={dueDate} onChange={e=>{setDueDate(e.target.value);setSaved(false);}}/></label><button className="button secondary" disabled={busy}>{saved?'Сохранено':'Сохранить'}</button>{error&&<p role="alert">{error}</p>}</form></div>;
}
export function Report({c,onPrepare}:{c:Case;onPrepare:()=>void}){return <section><div className="section-heading"><div><h2>Отчёт для клиента</h2><p>Проверенное сравнение, комментарий и уточнения в одном документе.</p></div></div><div className="workspace-report"><div><strong>polis.</strong><span>{c.demo?'Учебное предложение':'Страхование имущества'}</span></div><h2>{c.title}</h2><p>{c.client}</p><p>{c.requirements}</p><div className="report-offers">{c.offers.map(o=><div key={o.id}><span>{o.name}</span><strong>{isCurrent(c)?o.cells.premium.value:'Ожидает анализа'}</strong></div>)}</div><h3>Уточнения</h3>{isCurrent(c)?caseQuestions(c).map(q=><p key={q.id}><strong>{q.resolved?'Ответ отмечен':'Открыто'}:</strong> {q.offer} · {q.title}</p>):<p>Обновите анализ, чтобы включить актуальные вопросы.</p>}</div><div className="report-readiness"><ShieldCheck size={22}/><p>{allReviewed(c)?'Все условия отмечены как проверенные. Можно подготовить экспорт.':'Перед экспортом проверьте все условия. Открытые вопросы останутся в отчёте.'}</p></div><button className="button primary" disabled={!isCurrent(c)||c.offers.length<2} onClick={onPrepare}><FileText size={18}/>Проверка и экспорт</button></section>;}
export function History({c}:{c:Case}){const history=[...(c.activity||[])].reverse();return <><div className="section-heading"><div><h2>История заявки</h2><p>Загрузка документов, анализ и подтверждённые действия.</p></div></div><div className="workspace-history">{history.length?history.map(event=><div key={event.id}><Clock size={17}/><div><strong>{event.text}</strong><time>{new Date(event.at).toLocaleString('ru-RU')}</time></div></div>):<p className="workspace-note">Для этой заявки ещё нет записей в новом журнале. Следующие действия будут сохранены.</p>}</div>{c.changes.length>0&&<><div className="section-heading"><h2>Изменения последнего анализа</h2></div><div className="changes-list">{c.changes.map((change,i)=><div className="change-row" key={i}><div><strong>{change.field}</strong><span>{change.offer}</span></div><del>{change.before}</del><ArrowRight size={20}/><ins>{change.after}</ins></div>)}</div></>}</>;}
export function Clarifications({c,busy,onResolve}:{c:Case;busy:boolean;onResolve:(id:string,resolved:boolean)=>void}){return <div className="workspace-clarifications">{caseQuestions(c).map(q=><label key={q.id}><input type="checkbox" checked={q.resolved} disabled={busy||!isCurrent(c)} onChange={e=>onResolve(q.id,e.target.checked)}/><span><strong>{q.offer} · {q.title}</strong><small>{q.text}</small></span><span className="badge">{q.resolved?'Ответ отмечен':'Открыто'}</span></label>)}</div>;}
export function Attachments({c,busy,onUpload,onRole}:{c:Case;busy:boolean;onUpload:(file:File,role:DocumentRole)=>Promise<void>;onRole:(id:string,role:DocumentRole)=>void}){
 const [file,setFile]=useState<File|null>(null);const [role,setRole]=useState<DocumentRole>('requirements');const [error,setError]=useState('');const [inputKey,setInputKey]=useState(0);
 return <section className="workspace-attachments"><div className="section-heading"><div><h2>Материалы заявки</h2><p>Требования дополняют запрос клиента; полис, правила и переписка служат контекстом.</p></div></div>{c.attachments?.map(d=><div className="attachment-row" key={d.id}><FilePdf size={22}/><a href={`/api/documents/${d.id}`} target="_blank" rel="noreferrer">{d.name}<small>{d.pages} стр.</small></a><select aria-label={`Роль ${d.name}`} value={d.role} disabled={busy||c.demo} onChange={e=>onRole(d.id,e.target.value as DocumentRole)}>{Object.entries(DOCUMENT_ROLES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>)}{!c.demo&&<form className="attachment-form" onSubmit={async e=>{e.preventDefault();if(!file)return;setError('');try{await onUpload(file,role);setFile(null);setInputKey(k=>k+1);}catch(e){setError((e as Error).message);}}}><label className="field">Тип документа<select value={role} onChange={e=>setRole(e.target.value as DocumentRole)}>{Object.entries(DOCUMENT_ROLES).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field">PDF до 12 МБ<input key={inputKey} type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button secondary" disabled={!file||busy||(c.attachments?.length||0)>=6}><Plus size={16}/>Добавить материал</button>{error&&<p role="alert">{error}</p>}</form>}<p className="workspace-note">До 6 материалов. При изменении файла или его роли требуется повторный анализ и проверка. Анализ и чат получают актуальные PDF.</p></section>;
}
